apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-{{.APP_NAME}}
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronimage
            image: {{.IMAGE_NAME}}
            imagePullPolicy: Always
          restartPolicy: Never